### ISSUE TITLE
Artifactory Repository Broken

### ISSUE THREAD

**Issue by msullivan101** [bambora/na-ios-checkout#15]
During integration, step 1, attempting to execute the following command:
`pod repo-art add bambora-na-public "https://beanstream.jfrog.io/beanstream/api/pods/na-public"`
Returns an error:

> Retrieving index from 'https://beanstream.jfrog.io/beanstream/api/pods/na-public' into local spec repo 'bambora-na-public'
> [!] Error getting the index from Artifactory at: 'https://beanstream.jfrog.io/beanstream/api/pods/na-public' : [!] /usr/bin/curl -n -f -L -o /Users/msullivan/.cocoapods/repos-art/bambora-na-public/Specs/file.tgz https://beanstream.jfrog.io/beanstream/api/pods/na-public/index/fetchIndex --create-dirs
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (22) The requested URL returned error: 404 Not Found

**Comment by svenresch** [comment]
Sorry for the inconvenience. While we work to sort this out you should be able to substitute repo name and path and use the following.

pod repo-art add beanstream-public "https://beanstream.artifactoryonline.com/beanstream/api/pods/beanstream-public"

**Comment by msullivan101** [comment]
That worked.  Thanks!
