### ISSUE TITLE
keyboard word correction and spell checking

### ISSUE THREAD

**Issue by CBDev1** [bambora/na-ios-checkout#4]
"Correction" and "Spell Checking" should be turned off for all data entry fields. Very annoying when it keeps automatically changing my email address, street, name, etc

**Comment by svenresch** [comment]
Thx CBDev1! That'll be an easy fix. Will talk to the team to schedule getting this done asap and will get back to you with the plan.

**Comment by CBDev1** [comment]
@svenresch any update on applying this easy fix? Thanks!

**Comment by svenresch** [comment]
Fixed on v0.4.0 and available on the Develop branch. Will promote to Master inside of a few weeks.
