### ISSUE TITLE
Text Fields on real device do not render correctly

### ISSUE THREAD

**Issue by CBDev1** [bambora/na-ios-checkout#5]
When opening PayForm on a real iOS device (iPhone 6 Plus running iOS 9), it looks like the screenshot below.

When running on simulator, it looks as it should.

![screen shot 2016-11-28 at 6 45 27 pm](https://cloud.githubusercontent.com/assets/22161071/20690885/3df647b4-b59b-11e6-9502-fb6c5a80ef04.png)

**Comment by dlight-bean** [comment]
I could not reproduce this on our end. A couple of questions to help troubleshoot. 
Are you using our test app or your own? 
Have you tried it on any other devices or iOS versions?
Which version of iOS 9 (9.1, 9.2, 9.3)?

**Comment by CBDev1** [comment]
This is on iOS 8.1.x
All other PayForm functionality appears to work on this device.

**Comment by svenresch** [comment]
v0.4.0 (currently available on the "develop" branch) has been updated to indicate a minimum support level of iOS 9+.
